#### Preamble ####
# Purpose: Clean the data from from the Womens´s Pockets are Inferior paper by Jan Diehm & Amber Thomas.  
# Author: Hari Lee Robledo
# Date: April 2 2023 
# Contact: hari.leerobledo@mail.utoronto.ca 
# License: MIT
# Pre-requisites: 01-download_data.R

```{r}
#### Workspace setup ####
library(tidyverse)
library(jsonlite)
library(readr)
library(janitor)
library(dplyr)

```

```{r}
#### Clean data ####

# Code referenced from:https://tellingstorieswithdata.com/02-drinking_from_a_fire_hose.html

raw_pockets_data<-
  read_csv(
    file = here::here("data/raw_data/raw_pockets_data.csv"),
    show_col_types = FALSE
  )

# Change the name of the raw data into the clean data
cleaned_pockets_data <-
  clean_names(raw_pockets_data)

# Select the rows of interest
cleaned_pockets_data <-
  cleaned_pockets_data |>
  select(
    brand,
    style,
    men_women,
    price
  ) 

cleaned_pockets_data

# Code referenced from: chat.openai.com 

# Clean json file (pocket area measurements)
json_file <- here::here("data/raw_data/pocket_area_data.json")

# Read the JSON data from the file
pocket_area_data <- fromJSON(json_file)

# Change the name of the raw data into the clean data
cleaned_pocket_area_data <-
  clean_names(pocket_area_data)

# Select the rows of interest
cleaned_pocket_area_data <-
  cleaned_pocket_area_data |>
  select(
    updated_style,
    group,
    price_group,
    pocket_area
  ) 

cleaned_pocket_area_data
```

```{r}
#### Save cleaned data ####
# Code referenced from:https://tellingstorieswithdata.com/02-drinking_from_a_fire_hose.html

# save cleaned pockets data 
write_csv(
  x = cleaned_pockets_data,
  file = here::here("data/analysis_data/cleaned_pockets_data.csv")
)

# save json cleaned data (pocket area measurements)

# Change from json format to csv
csv_file <- here::here("data/analysis_data/cleaned_pocket_area_data.csv")

# Write the cleaned data frame to a CSV file
write_csv(cleaned_pocket_area_data, csv_file)


```

